name: android_content_resolver_example
description: Demonstrates how to use the android_content_provider plugin.
publish_to: 'none'

environment:
  sdk: ">=2.15.0-233.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.2.0
  flutter_riverpod: ^2.2.0
  hooks_riverpod: ^2.2.0
  flutter_hooks: ^0.18.6
  permission_handler: ^10.2.0

  android_content_provider:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
