name: android_content_resolver_example
description: Demonstrates how to use the android_content_provider plugin.
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.1
  permission_handler: ^10.4.3

  android_content_provider:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
