include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    public_member_api_docs: true
    prefer_const_constructors: true
    constant_identifier_names: false
