// Autogenerated from Pigeon (v1.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name
// @dart = 2.12
import 'dart:async';
import 'dart:typed_data' show Uint8List, Int32List, Int64List, Float64List;

import 'package:flutter/foundation.dart' show WriteBuffer, ReadBuffer;
import 'package:flutter/services.dart';

class CreateMessage {
  String? authority;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['authority'] = authority;
    return pigeonMap;
  }

  static CreateMessage decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return CreateMessage()
      ..authority = pigeonMap['authority'] as String?;
  }
}

class GetTypeMessage {
  String? authority;
  String? uri;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['authority'] = authority;
    pigeonMap['uri'] = uri;
    return pigeonMap;
  }

  static GetTypeMessage decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return GetTypeMessage()
      ..authority = pigeonMap['authority'] as String?
      ..uri = pigeonMap['uri'] as String?;
  }
}

class _ContentProviderApiCodec extends StandardMessageCodec {
  const _ContentProviderApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is CreateMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else 
    if (value is GetTypeMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else 
{
      super.writeValue(buffer, value);
    }
  }
  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return CreateMessage.decode(readValue(buffer)!);
      
      case 129:       
        return GetTypeMessage.decode(readValue(buffer)!);
      
      default:      
        return super.readValueOfType(type, buffer);
      
    }
  }
}
abstract class ContentProviderApi {
  static const MessageCodec<Object?> codec = _ContentProviderApiCodec();

  void create(CreateMessage message);
  String getType(GetTypeMessage message);
  static void setup(ContentProviderApi? api) {
    {
      const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ContentProviderApi.create', codec);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null, 'Argument for dev.flutter.pigeon.ContentProviderApi.create was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final CreateMessage? arg_message = args[0] as CreateMessage?;
          assert(arg_message != null, 'Argument for dev.flutter.pigeon.ContentProviderApi.create was null, expected non-null CreateMessage.');
          api.create(arg_message!);
          return;
        });
      }
    }
    {
      const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ContentProviderApi.getType', codec);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null, 'Argument for dev.flutter.pigeon.ContentProviderApi.getType was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final GetTypeMessage? arg_message = args[0] as GetTypeMessage?;
          assert(arg_message != null, 'Argument for dev.flutter.pigeon.ContentProviderApi.getType was null, expected non-null GetTypeMessage.');
          final String output = api.getType(arg_message!);
          return output;
        });
      }
    }
  }
}
